import {Request, Response} from 'express';
import SalesService from './sales.service';
import {AppError} from '../../errors/appError';
import {getTenantId} from '../shared/utils/getTenantId';
import {createSaleSchema, cancelSaleSchema, settleSaleSchema} from './schemas/create.sales';
import {SaleStatus} from './sales/enums/sale-status';
import CustomerService from '../customers/customer.service';

const parseId = (value: string | string[]) => {if (Array.isArray(value)) throw new AppError('Identificador inválido', 400); const id = Number(value); if (!Number.isInteger(id) || id <= 0) throw new AppError('Identificador inválido', 400); return id;};
const queryString = (value: unknown) => typeof value === 'string' ? value.trim() : undefined;
const isoToday = () => new Date().toISOString().slice(0, 10);
const addDays = (iso: string, days: number) => {const d = new Date(`${iso}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + days); return d.toISOString().slice(0, 10);};

const SalesController = {
  create: async (req: Request, res: Response) => {try {const tenantId = getTenantId(req); if (!req.session?.user?.id) return res.status(401).send(); const sale = await SalesService.create(createSaleSchema.parse(req.body), tenantId, req.session.user.id); return res.status(201).json(sale);} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  findMany: async (req: Request, res: Response) => {try {const tenantId = getTenantId(req); const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)); const status = queryString(req.query.status) as SaleStatus | undefined; const customerId = req.query.customerId ? parseId(String(req.query.customerId)) : undefined; const search = queryString(req.query.search); return res.status(200).json(await SalesService.findMany(tenantId, {page, limit, status, customerId, search}));} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  getReceivables: async (req: Request, res: Response) => {try {const today = isoToday(); const from = queryString(req.query.from) || today; const to = queryString(req.query.to) || addDays(today, 7); return res.status(200).json(await SalesService.getReceivables({tenantId: getTenantId(req), from, to}));} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  findById: async (req: Request, res: Response) => {try {const sale = await SalesService.findById(parseId(req.params.id), getTenantId(req)); if (!req.accepts('json')) return res.status(200).render('sales/show', {sale: sale.toJSON(), today: isoToday(), error: null}); return res.status(200).json(sale);} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(500).json({message: 'Erro interno do servidor'});}},
  cancel: async (req: Request, res: Response) => {try {if (!req.session?.user?.id) return res.status(401).send(); const data = cancelSaleSchema.parse(req.body); await SalesService.cancel(parseId(req.params.id), getTenantId(req), req.session.user.id, data.reason); return res.status(204).send();} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  registerPayment: async (req: Request, res: Response) => {try {const result = await SalesService.registerPayment(parseId(req.params.installmentId), parseId(req.params.id), getTenantId(req), new Date()); return res.status(200).json({message: 'Pagamento registrado com sucesso', installment: {id: result.installment.id, status: result.installment.status, paidAmountCents: result.installment.paidAmountCents, paidAt: result.installment.paidAt}, saleCompleted: result.saleCompleted});} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  settle: async (req: Request, res: Response) => {try {if (!req.session?.user?.id) return res.status(401).send(); const data = settleSaleSchema.parse(req.body); const settlement = await SalesService.settle(parseId(req.params.id), getTenantId(req), {...data, settledBy: req.session.user.id}); return res.status(201).json(settlement);} catch (error: unknown) {if (error instanceof AppError) return res.status(error.statusCode).json({message: error.message}); return res.status(400).json({message: error instanceof Error ? error.message : 'Requisição inválida'});}},
  pageList: async (req: Request, res: Response) => {try {const tenantId = getTenantId(req); const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)); const status = queryString(req.query.status) as SaleStatus | undefined; const search = queryString(req.query.search); const today = isoToday(); const from = queryString(req.query.from) || today; const to = queryString(req.query.to) || addDays(today, 7); const [result, customers, receivables] = await Promise.all([SalesService.findMany(tenantId, {page, limit, status, search}), CustomerService.findAll(tenantId), SalesService.getReceivables({tenantId, from, to})]); const customerMap = new Map(customers.map(customer => [customer.id, customer])); const sales = result.data.map(sale => ({...sale.toJSON(), customer: customerMap.get(sale.customerId) ?? null})); return res.render('sales/index', {sales, pagination: result.pagination, groupedReceivables: receivables.grouped, receivableSummary: receivables.summary, today: receivables.today, search: search || '', status: status || '', from, to, error: null});} catch (error: unknown) {console.error(error); return res.status(500).render('sales/index', {sales: [], pagination: null, groupedReceivables: {}, receivableSummary: {overdueTotal: 0, todayTotal: 0, upcomingTotal: 0}, today: isoToday(), search: '', status: '', from: isoToday(), to: addDays(isoToday(), 7), error: error instanceof Error ? error.message : 'Não foi possível carregar as vendas.'});}},
};
export default SalesController;
